### ISSUE TITLE
Add a way to tag certain changes in changesets as additions, changes and removals to the integrations

### ISSUE THREAD

**Issue by tombruijn** [appsignal/mono#31]
https://github.com/appsignal/integration-guide/blob/main/roadmap.md#syncing-with-team-content

I'm thinking another metadata in the markdown YAML based on the [keep a changelog format](https://keepachangelog.com/en/1.0.0/):

```yaml
---
bump: minor
type: fix/add/change/remove # This metadata is new here
---

My changeset entry.
```

## To do

- [x] Add frontmatter (metadata) field for `type` to changesets. See the values below.
    - [x] For `mono changeset add`. Add prompt that asks for the type of change.
    - [x] For the parsing of changesets.
- [x] Update changelog format to add different sections.
    - Supported sections for "Fixed" (`fixed`), "Added" (`added`), "Changed" (`changed`), "Removed" (`removed`), "Deprecated" (`deprecated`) and "Security" (`security`)

## Discussion

- For the "deprecated" type of change we may need to create two changesets if we added replacement functionality. That could be a "changed" changeset entry and a separate "deprecated" one.
